### ISSUE TITLE
add simple vignette/example

### ISSUE THREAD

**Issue by stephens999** [surbut/matrix_ash#5]
I think the next step is to add a simple vignette/example that I can run for myself.
Ideally you want it to be self-contained and as simple as possible to illustrate the method. 
So, not reading in data from other files etc.

**Comment by surbut** [comment]
resolved by adding simulated data for 5 tissues, strong t stats and training/test level bhats. For the mean time, use svd internally to generate 'eigen factors' to give the user an idea but I don't use them. please try  at your leisrure - it's in 'vignettes/separatingtrainingandtesting

**Comment by surbut** [comment]
resolved - framework with factor sim tied into vignette
