### ISSUE TITLE
export functions needed

### ISSUE THREAD

**Issue by stephens999** [surbut/matrix_ash#7]
can you export functions like
compute.hm.train
compute.covmat

that you need in the Vignette, so I can run them without sourcing the code?
Then replace "source()" with library(mash) in the vignette.
Sourcing the code is something we need to move away from...

**Comment by surbut** [comment]
Exporting was not working yesterday - I'm meeting with Raman at 1:30 today to resolve. Did you run the simulation though successfully?

**Comment by surbut** [comment]
The package load is fixed.
